/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class jerome_Jerome_Completion */

#ifndef _Included_jerome_Jerome_Completion
#define _Included_jerome_Jerome_Completion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jerome_Jerome_Completion
 * Method:    succeeded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_00024Completion_succeeded
  (JNIEnv *, jobject);

/*
 * Class:     jerome_Jerome_Completion
 * Method:    canceled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_00024Completion_canceled
  (JNIEnv *, jobject);

/*
 * Class:     jerome_Jerome_Completion
 * Method:    interrupted
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_00024Completion_interrupted
  (JNIEnv *, jobject);

/*
 * Class:     jerome_Jerome_Completion
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_00024Completion_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
