/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jerome_NativePointer */

#ifndef _Included_jerome_NativePointer
#define _Included_jerome_NativePointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jerome_NativePointer
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jerome_NativePointer_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
