/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jerome_Jerome */

#ifndef _Included_jerome_Jerome
#define _Included_jerome_Jerome
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jerome_Jerome
 * Method:    loadModel
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljerome/Jerome/ModelLoaderCallback;)V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_loadModel
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     jerome_Jerome
 * Method:    collectionWasUpdated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_collectionWasUpdated
  (JNIEnv *, jobject);

/*
 * Class:     jerome_Jerome
 * Method:    collectionWasUpdatedInState
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_collectionWasUpdatedInState
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jerome_Jerome
 * Method:    utteranceWithID
 * Signature: (Ljava/lang/String;)Ljerome/Utterance;
 */
JNIEXPORT jobject JNICALL Java_jerome_Jerome_utteranceWithID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jerome_Jerome
 * Method:    resetDialogue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_resetDialogue
  (JNIEnv *, jobject);

/*
 * Class:     jerome_Jerome
 * Method:    tossDialogueToStateWithName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_tossDialogueToStateWithName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jerome_Jerome
 * Method:    respondTo
 * Signature: (Ljava/lang/String;Ljerome/Jerome/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_jerome_Jerome_respondTo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jerome_Jerome
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jerome_Jerome_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
