/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jerome_Jerome_ModelLoaderCallback */

#ifndef _Included_jerome_Jerome_ModelLoaderCallback
#define _Included_jerome_Jerome_ModelLoaderCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
